runtime: nodejs10

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'postgres'
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'datecuen231068'
  INSTANCE_CONNECTION_NAME: 'strapi-284607:europe-west4:strapi'

beta_settings:
  cloud_sql_instances: 'strapi'